spring.application.name=majorprojectecopulse

server.port=${PORT:10000}
server.address=0.0.0.0
server.forward-headers-strategy=framework

spring.data.mongodb.uri=${MONGO_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

logging.level.com.carbonest=INFO
logging.level.org.springframework.security=INFO