# Server
server.port=${PORT:8080}
server.address=0.0.0.0
spring.application.name=majorprojectecopulse

# MongoDB
spring.data.mongodb.uri=mongodb+srv://ecopulse_user:ishu123@ecopulse-cluster.remmimg.mongodb.net/ecopulse?retryWrites=true&w=majority

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# CORS
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# Logging
logging.level.com.carbonest=INFO
logging.level.org.springframework.security=INFO