spring.application.name=majorprojectecopulse

server.port=${PORT:8080}
server.address=0.0.0.0
server.forward-headers-strategy=framework

spring.data.mongodb.uri=mongodb+srv://ecopulse_user:ishu123@ecopulse-cluster.remmimg.mongodb.net/ecopulse?retryWrites=true&w=majority

jwt.secret=CarbonEst_SuperSecret_Key_Min32Chars_2024!
jwt.expiration=604800000

logging.level.com.carbonest=INFO
logging.level.org.springframework.security=INFO
logging.level.root=ERROR
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.main.lazy-initialization=true
server.tomcat.accept-count=100
server.tomcat.threads.max=10

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always